name: pull-request-integration

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [develop, master]
    
concurrency:
  group: cloud-integration-tests
  cancel-in-progress: false

env:
  ZPA_CLIENT_ID: ${{ secrets.ZPA_CLIENT_ID }}
  ZPA_CLIENT_SECRET: ${{ secrets.ZPA_CLIENT_SECRET }}
  ZPA_CUSTOMER_ID: ${{ secrets.ZPA_CUSTOMER_ID }}

jobs:
  integration:
    # Require reviewers for this environment
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    environment: integration

    runs-on: ubuntu-latest

    steps:
      - name: Perform testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          # ansible-core-version:
          git-checkout-ref: ${{ github.event.pull_request.head.sha }} # Check out the pull request
          pre-test-cmd: >- # Configure integration test run
            python ./tests/utils/render.py
          python-version: 3.9
          target-python-version: 3.9
          testing-type: integration
          test-deps: community.general
